name: CI/CD for Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push frontend Docker image
      run: |
        docker build -t registry.render.com/${{ secrets.RENDER_ACCOUNT_NAME }}/frontend:latest ./frontend
        docker login -u _ -p ${{ secrets.RENDER_API_KEY }} registry.render.com
        docker push registry.render.com/${{ secrets.RENDER_ACCOUNT_NAME }}/frontend:latest

    - name: Build and push backend Docker image
      run: |
        docker build -t registry.render.com/${{ secrets.RENDER_ACCOUNT_NAME }}/backend:latest ./backend
        docker push registry.render.com/${{ secrets.RENDER_ACCOUNT_NAME }}/backend:latest

    - name: Trigger Render deployment
      run: |
        curl -X POST https://api.render.com/deploy/sync \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -d '{
          "serviceId": "${{ secrets.RENDER_SERVICE_ID }}"
        }'
